const express=require("express"),path=require("path"),fs=require("fs"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),cors=require("cors");
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||"srp-dev-secret";
const DB=path.join(__dirname,"data.json");
app.use(cors());app.use(express.json({limit:"5mb"}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,"public")));
function seed(){
 if(fs.existsSync(DB))return JSON.parse(fs.readFileSync(DB));
 const db={users:[],vendors:[
  {id:"v1",name:"SRP Fashion Hub",email:"fashion@srp.local",phone:"9876543210",status:"approved",rating:4.7,orders:128,revenue:245900},
  {id:"v2",name:"HomeKart India",email:"home@srp.local",phone:"9876543211",status:"approved",rating:4.5,orders:96,revenue:173400},
  {id:"v3",name:"Tech Bazaar",email:"tech@srp.local",phone:"9876543212",status:"pending",rating:4.3,orders:31,revenue:89400}
 ],products:[
  {id:"p1",vendorId:"v1",title:"Premium Cotton Casual Shirt",category:"Fashion",price:699,mrp:1299,stock:74,rating:4.6,sales:143,image:"https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=700&q=80",status:"active"},
  {id:"p2",vendorId:"v1",title:"Women Printed Kurti",category:"Fashion",price:599,mrp:1199,stock:42,rating:4.5,sales:201,image:"https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=700&q=80",status:"active"},
  {id:"p3",vendorId:"v2",title:"Modern Kitchen Storage Set",category:"Home",price:449,mrp:899,stock:118,rating:4.4,sales:187,image:"https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=700&q=80",status:"active"},
  {id:"p4",vendorId:"v3",title:"Wireless Bluetooth Headphones",category:"Electronics",price:999,mrp:1999,stock:27,rating:4.2,sales:76,image:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=80",status:"active"}
 ],orders:[],carts:{},reviews:[],settings:{freeShipping:999,shippingFee:49,gst:0},notifications:[]};
 fs.writeFileSync(DB,JSON.stringify(db,null,2));return db;
}
let db=seed();const save=()=>fs.writeFileSync(DB,JSON.stringify(db,null,2));
const id=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function token(user){return jwt.sign({id:user.id,email:user.email,role:user.role,vendorId:user.vendorId},SECRET,{expiresIn:"7d"})}
function auth(req,res,next){try{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))throw 0;req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:"Authentication required"})}}
function role(...roles){return (req,res,next)=>{if(!roles.includes(req.user.role))return res.status(403).json({error:"Permission denied"});next()}}
function publicProduct(p){return p}
app.get("/api/health",(req,res)=>res.json({ok:true,service:"SRP Shopping",time:new Date().toISOString()}));
app.get("/api/products",(req,res)=>{let a=db.products.filter(p=>p.status==="active");const q=(req.query.q||"").toLowerCase(),cat=req.query.category||"";if(q)a=a.filter(p=>(p.title+" "+p.category).toLowerCase().includes(q));if(cat&&cat!=="All")a=a.filter(p=>p.category===cat);if(req.query.sort==="priceLow")a.sort((x,y)=>x.price-y.price);if(req.query.sort==="priceHigh")a.sort((x,y)=>y.price-x.price);if(req.query.sort==="rating")a.sort((x,y)=>y.rating-x.rating);res.json(a)});
app.get("/api/products/:id",(req,res)=>{const p=db.products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:"Product not found"});res.json({...p,vendor:db.vendors.find(v=>v.id===p.vendorId)})});
app.get("/api/categories",(req,res)=>res.json(["All","Fashion","Electronics","Home","Beauty","Grocery","Mobiles","Appliances","Toys","Sports"]));
app.get("/api/vendors",(req,res)=>res.json(db.vendors.filter(v=>v.status==="approved")));
app.post("/api/auth/register",(req,res)=>{const {name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:"All fields required"});if(db.users.some(u=>u.email===email))return res.status(409).json({error:"Email already registered"});const u={id:id("u"),name,email,password:bcrypt.hashSync(password,10),role:"customer"};db.users.push(u);save();res.json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post("/api/auth/login",(req,res)=>{const {email,password}=req.body;let u=db.users.find(x=>x.email===email);if(!u&&email===process.env.ADMIN_EMAIL||(!u&&email==="admin@srpshopping.local")){u={id:"admin",name:"SRP Administrator",email,role:"admin",password:bcrypt.hashSync(process.env.ADMIN_PASSWORD||"Admin@12345",10)};db.users.push(u);save()}if(!u||!bcrypt.compareSync(password,u.password))return res.status(401).json({error:"Invalid email or password"});res.json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,vendorId:u.vendorId}})});
app.get("/api/me",auth,(req,res)=>{const u=db.users.find(x=>x.id===req.user.id);res.json(u?{id:u.id,name:u.name,email:u.email,role:u.role,vendorId:u.vendorId}:req.user)});
app.get("/api/cart",auth,(req,res)=>{const cart=db.carts[req.user.id]||[];res.json(cart.map(i=>({...i,product:db.products.find(p=>p.id===i.productId)})))});
app.post("/api/cart",auth,(req,res)=>{const {productId,qty=1}=req.body,p=db.products.find(x=>x.id===productId);if(!p)return res.status(404).json({error:"Product not found"});if(qty<1||qty>p.stock)return res.status(400).json({error:"Invalid quantity"});let c=db.carts[req.user.id]||[],i=c.find(x=>x.productId===productId);if(i)i.qty=Math.min(p.stock,i.qty+qty);else c.push({productId,qty});db.carts[req.user.id]=c;save();res.json(c)});
app.put("/api/cart/:productId",auth,(req,res)=>{let c=db.carts[req.user.id]||[],i=c.find(x=>x.productId===req.params.productId);if(!i)return res.status(404).json({error:"Not in cart"});const p=db.products.find(x=>x.id===i.productId);i.qty=Math.max(1,Math.min(p.stock,Number(req.body.qty)));save();res.json(c)});
app.delete("/api/cart/:productId",auth,(req,res)=>{db.carts[req.user.id]=(db.carts[req.user.id]||[]).filter(x=>x.productId!==req.params.productId);save();res.json({ok:true})});
app.post("/api/orders",auth,(req,res)=>{const {address,paymentMethod}=req.body;if(!address||!paymentMethod)return res.status(400).json({error:"Address and payment method required"});const c=db.carts[req.user.id]||[];if(!c.length)return res.status(400).json({error:"Cart is empty"});let subtotal=0,items=[];for(const i of c){const p=db.products.find(x=>x.id===i.productId);if(!p||p.stock<i.qty)return res.status(400).json({error:"Stock unavailable"});subtotal+=p.price*i.qty;items.push({productId:p.id,title:p.title,qty:i.qty,price:p.price,vendorId:p.vendorId})}const shipping=subtotal>=db.settings.freeShipping?0:db.settings.shippingFee,total=subtotal+shipping;items.forEach(i=>{db.products.find(p=>p.id===i.productId).stock-=i.qty});const o={id:id("ord_"),number:"SRP"+Date.now().toString().slice(-10),userId:req.user.id,items,address,paymentMethod,subtotal,shipping,total,status:"PLACED",createdAt:new Date().toISOString(),tracking:"Preparing shipment"};db.orders.unshift(o);db.carts[req.user.id]=[];save();res.json(o)});
app.get("/api/orders",auth,(req,res)=>res.json(req.user.role==="admin"?db.orders:db.orders.filter(o=>o.userId===req.user.id)));
app.post("/api/sellers/apply",(req,res)=>{const {name,email,phone}=req.body;if(!name||!email)return res.status(400).json({error:"Name and email required"});const v={id:id("v"),name,email,phone,status:"pending",rating:0,orders:0,revenue:0};db.vendors.push(v);save();res.json(v)});
app.get("/api/admin/stats",auth,role("admin"),(req,res)=>{const revenue=db.orders.reduce((s,o)=>s+o.total,0);res.json({users:db.users.filter(u=>u.role==="customer").length,vendors:db.vendors.length,pendingVendors:db.vendors.filter(v=>v.status==="pending").length,products:db.products.length,orders:db.orders.length,revenue,lowStock:db.products.filter(p=>p.stock<10).length})});
app.get("/api/admin/vendors",auth,role("admin"),(req,res)=>res.json(db.vendors));
app.patch("/api/admin/vendors/:id",auth,role("admin"),(req,res)=>{const v=db.vendors.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:"Vendor not found"});Object.assign(v,req.body);save();res.json(v)});
app.get("/api/admin/products",auth,role("admin"),(req,res)=>res.json(db.products));
app.post("/api/admin/products",auth,role("admin"),(req,res)=>{const p={id:id("p"),status:"active",rating:0,sales:0,...req.body,price:Number(req.body.price),mrp:Number(req.body.mrp),stock:Number(req.body.stock)};db.products.push(p);save();res.json(p)});
app.patch("/api/admin/products/:id",auth,role("admin"),(req,res)=>{const p=db.products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:"Product not found"});Object.assign(p,req.body);save();res.json(p)});
app.delete("/api/admin/products/:id",auth,role("admin"),(req,res)=>{db.products=db.products.filter(x=>x.id!==req.params.id);save();res.json({ok:true})});
app.get("/api/admin/orders",auth,role("admin"),(req,res)=>res.json(db.orders));
app.patch("/api/admin/orders/:id",auth,role("admin"),(req,res)=>{const o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:"Order not found"});Object.assign(o,req.body);save();res.json(o)});
app.get("/api/seller/dashboard",auth,role("seller","admin"),(req,res)=>{const vid=req.user.vendorId||req.query.vendorId,ps=db.products.filter(p=>p.vendorId===vid),os=db.orders.filter(o=>o.items.some(i=>i.vendorId===vid));res.json({vendor:db.vendors.find(v=>v.id===vid),products:ps,orders:os,stats:{products:ps.length,stock:ps.reduce((s,p)=>s+p.stock,0),orders:os.length,revenue:os.reduce((s,o)=>s+o.items.filter(i=>i.vendorId===vid).reduce((a,i)=>a+i.price*i.qty,0),0)}})});
app.post("/api/seller/products",auth,role("seller","admin"),(req,res)=>{const vendorId=req.user.vendorId||req.body.vendorId;if(!vendorId)return res.status(400).json({error:"Vendor account required"});const p={id:id("p"),vendorId,status:"active",rating:0,sales:0,...req.body,price:Number(req.body.price),mrp:Number(req.body.mrp),stock:Number(req.body.stock)};db.products.push(p);save();res.json(p)});
app.patch("/api/seller/products/:id",auth,role("seller","admin"),(req,res)=>{const p=db.products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:"Not found"});if(req.user.role==="seller"&&p.vendorId!==req.user.vendorId)return res.status(403).json({error:"Forbidden"});Object.assign(p,req.body);save();res.json(p)});
app.patch("/api/seller/orders/:id",auth,role("seller","admin"),(req,res)=>{const o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:"Order not found"});if(req.user.role==="seller"&&!o.items.some(i=>i.vendorId===req.user.vendorId))return res.status(403).json({error:"Forbidden"});Object.assign(o,req.body);save();res.json(o)});
app.post("/api/seller/login",(req,res)=>{const {email,password}=req.body;let v=db.vendors.find(x=>x.email===email);if(!v||password!=="seller123")return res.status(401).json({error:"Use approved seller account and demo password seller123"});if(v.status!=="approved")return res.status(403).json({error:"Seller is not approved"});let u=db.users.find(x=>x.email===email);if(!u){u={id:id("s"),name:v.name,email:v.email,role:"seller",vendorId:v.id,password:bcrypt.hashSync(password,10)};db.users.push(u);save()}res.json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,vendorId:u.vendorId}})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log(`SRP Shopping running at http://localhost:${PORT}`));